# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

flutter_application_path = '../flutter/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'flutter_addtoapp_basic_ios' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  install_all_flutter_pods(flutter_application_path)

  # Pods for flutter_addtoapp_basic_ios

  target 'flutter_addtoapp_basic_iosTests' do
    inherit! :search_paths
    # Pods for testing
    install_all_flutter_pods(flutter_application_path)
  end

  target 'flutter_addtoapp_basic_iosUITests' do
    # Pods for testing
    install_all_flutter_pods(flutter_application_path)
  end

end
